server:
  port: 10002
  error:
    include-message: always

spring:
  application:
    name: coupon-customer-serv
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/geekbang_coupon_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: GeekbangCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8948
        service: coupon-customer-serv
        heart-beat-interval: 5000
        heart-beat-timeout: 20000
        metadata:
          mydata: abc
        naming-load-cache-at-start: false
        cluster-name: Cluster-A
        namespace: dev
        group: myGroup
        register-enabled: true
        watch:
          enabled: true
        watch-delay: 30000



logging:
  level:
    com.geekbang.coupon: debug